name: Production Build

on:
    push:
        branches: [ production ]
jobs: 
    release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install PHP dependencies
          run: composer install --prefer-dist --no-progress --no-suggest
        - name: Install front-end dependencies
          run: npm ci
        - name: Build front-end resources
          run: npm run build --if-present
        - name: Commit vendor and build files
          uses: EndBug/add-and-commit@v4
          with:
            author_name: David Lewis
            author_email: mail@david-lewis.com
            message: "Add vendor files"
            add: "vendor/* build/*"
            force: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      