name: Release

on:
    release: 
        types: [created]
jobs: 
    release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
            uses: actions/checkout@v2
        - name: Create a file
            run: echo "Test file" > testfile.txt 
        - name: Commit test
            uses: EndBug/add-and-commit@v4
            with:
            author_name: David Lewis
            author_email: mail@david-lewis.com
            message: "Automatic commit"
            add: "*.txt"
            force: true
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      